# Generated by Django 3.2.4 on 2021-07-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='stock',
            field=models.ManyToManyField(blank=True, related_name='stock_information', to='stock.Information'),
        ),
    ]
